### ISSUE TITLE
Database connection 

### ISSUE THREAD

**Issue by Gagan0643** [rahul-n18/rahul-n18#1]
Hlo sir, im facing problem in connecting mysql to netbeans, i'm not greeting where im wrong....Can u please resolve my issue since vtu has deadline till 10th to submit project..

**Comment by rahul-n18** [comment]
Hello Gagan, can you please open an Issue with the respected Repository so that I can help you with It

**Comment by Gagan0643** [comment]
Sir if you could give me your Instagram address or please tell me how to contact you, it will be so helpful for me to solve my query
